
server:
  port: 2002

eureka:
  server:
    enable-self-preservation: true
    peer-node-read-timeout-ms: 300
  instance:
    prefer-ip-address: true
    hostname: eureka2.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://test:test@127.0.0.2:2001/eureka/

spring:
  security:
    user:
      name: test
      password: test