##https://github.com/wangzhen320909/Eureka_New_2020.git
server:
  port: 3001


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:2001/eureka/,http://eureka2.com:2002/eureka/
#    availability-zones:
#      zone1: http://eureka1.com:2001/eureka/
###应用名称
spring:
  application:
    name: consume-first
